Plot layer features
BiAPoL/napari-stress pull request #132
Opened 2022-08-11 13:54 UTC by zoccoler

Hi Johannes @jo-mueller ,

This is my current implementation of the histogram of features, which could fix #99 .
Let me know if it works and if you have suggestions to improve it! As you suggested, I based it a lot on [napari-matplotlib.FeatureScatterWidget](https://github.com/matplotlib/napari-matplotlib/blob/308134b6dc568d88b7ac81d83fba25af8d2ed6fa/src/napari_matplotlib/scatter.py#L111).

Best,
Marcelo

2022-08-14 07:50 UTC, jo-mueller approved these changes
Hi @zoccoler ,

I love it :) I just changed the naming of the plugin a bit - further down the road there may be more visualization widgets and then it would be nice to have them grouped nicely by name. Thanks a lot for working on this!

2022-08-14 07:50 UTC, jo-mueller commented on src/napari_stress/napari.yaml
> +      title: Features Histogram
```suggestion
      title: Visualize features (histogram)
```

2022-08-14 07:50 UTC, jo-mueller commented on src/napari_stress/napari.yaml
> +      display_name: Features Histogram
```suggestion
      display_name: Visualize features (histogram)
```

2022-08-14 07:53 UTC, jo-mueller commented
Maybe as an addon - would it be difficult to add an `Export` button to the plugin? I guess the export function should then open a [FileSelectionDialogue](https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QFileDialog.html#PySide2.QtWidgets.PySide2.QtWidgets.QFileDialog.getSaveFileName) and call the `dataframe.to_csv()` function on that.

2022-08-14 07:55 UTC, jo-mueller requested changes
Maybe as an addon - would it be difficult to add an `Export` button to the plugin? I guess the export function should then open a [FileSelectionDialogue](https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QFileDialog.html#PySide2.QtWidgets.PySide2.QtWidgets.QFileDialog.getSaveFileName) and call the `dataframe.to_csv()` function on that.

2022-08-14 07:56 UTC, jo-mueller commented on src/napari_stress/_visualization/features_histogram.py
> +            n_bins={"value": 100, "widget_type": "SpinBox"},
```suggestion
            n_bins={"value": 50, "widget_type": "SpinBox"},
```

2022-08-14 07:57 UTC, jo-mueller commented on src/napari_stress/_visualization/features_histogram.py
> +            n_bins={"value": 100, "widget_type": "SpinBox"},
Just a matter of taste - feel free to also leave it as it is.

2022-08-14 08:04 UTC, jo-mueller commented on src/napari_stress/_visualization/features_histogram.py
> +            call_button="plot",
```suggestion
            call_button="Update",
```

2022-08-16 09:29 UTC, zoccoler commented
> Maybe as an addon - would it be difficult to add an `Export` button to the plugin? I guess the export function should then open a [FileSelectionDialogue](https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QFileDialog.html#PySide2.QtWidgets.PySide2.QtWidgets.QFileDialog.getSaveFileName) and call the `dataframe.to_csv()` function on that.

I implemented that now, could you give it a try? @jo-mueller . It saves the data displayed on the graph, not the whole data in `layer.features`. It made more sense to me since it comes along with the plotting widget, but we can change that later if you like or put this option somewhere else.

Default place to save is 'c:\\', it works in Windows, I don't know for other OS.

2022-08-16 17:59 UTC, jo-mueller approved these changes
Works like a charm! 

One tiny thing: Could you remove the `LBDV_at_Quad_Pts_...` files from the PR? They are generated on-the-fly by some under-the-hood stress code and I haven't yet added them to the gitignore ^^"

Feel free to merge.

2022-08-17 10:32 UTC, merged